import type { Product } from "./products";

/**
 * MOCK product catalog for the Belle Afrik storefront.
 *
 * Every product is invented for the demo build - names, prices, ratings and
 * copy are placeholders so the UI can be reviewed with realistic content.
 * No photography is used anywhere: <ProductArtwork /> renders each bottle as
 * an SVG from the `palette` + `shape` fields below.
 */
export const PRODUCTS: Product[] = [
  {
    id: "p-marula-glow-face-oil",
    slug: "marula-glow-face-oil",
    name: "Marula Glow Face Oil",
    tagline: "Cold-pressed marula for a lit-from-within finish",
    description:
      "Ninety-nine percent cold-pressed marula oil sinks in fast and leaves skin feeling cushioned rather than coated. Skin looks quietly luminous by morning.",
    price: 62,
    compareAtPrice: 72,
    category: "serums",
    concerns: ["hydration", "firming"],
    size: "30 ml",
    shape: "dropper",
    palette: {
      backdrop: "#f7e8d9",
      bottle: "#e6c795",
      cap: "#7c6a4f",
      accent: "#fffbf4",
    },
    keyIngredients: [
      { name: "Marula oil", benefit: "Omega-rich moisture that absorbs quickly" },
      { name: "Squalane", benefit: "Weightless barrier support" },
      { name: "Vitamin E", benefit: "Defends against daily oxidative stress" },
    ],
    howToUse: [
      "Warm 3-4 drops between your palms.",
      "Press into clean, slightly damp skin.",
      "Follow with a moisturizer to seal everything in.",
    ],
    rating: 4.9,
    reviewCount: 842,
    badges: ["Vegan", "Cold-pressed"],
    skinTypes: ["Normal", "Dry", "Combination"],
    stockNote: "Ships in 1-2 business days",
    isBestSeller: true,
  },
  {
    id: "p-baobab-hydration-serum",
    slug: "baobab-hydration-serum",
    name: "Baobab Hydration Serum",
    tagline: "A drink of water for thirsty skin",
    description:
      "Baobab seed extract pairs with triple-weight hyaluronic acid to pull moisture through every layer of the skin. Lightweight enough for layering, rich enough to notice.",
    price: 58,
    category: "serums",
    concerns: ["hydration", "soothing"],
    size: "30 ml",
    shape: "dropper",
    palette: {
      backdrop: "#e8f0e9",
      bottle: "#cfe0d2",
      cap: "#5d6b4f",
      accent: "#fcfdfb",
    },
    keyIngredients: [
      { name: "Baobab seed extract", benefit: "Tree-grown hydration and vitamin C" },
      { name: "Hyaluronic acid", benefit: "Holds water in the upper layers" },
      { name: "Panthenol", benefit: "Calms tight, stressed skin" },
    ],
    howToUse: [
      "Apply 2-3 drops to damp skin, morning and night.",
      "Pat - do not rub - until absorbed.",
      "Layer under oil or cream.",
    ],
    rating: 4.8,
    reviewCount: 611,
    badges: ["Vegan", "Fragrance-free"],
    skinTypes: ["All skin types", "Dehydrated"],
    stockNote: "Ships in 1-2 business days",
    isBestSeller: true,
    isNew: true,
  },
  {
    id: "p-shea-cloud-moisturizer",
    slug: "shea-cloud-moisturizer",
    name: "Shea Cloud Moisturizer",
    tagline: "Whipped shea that melts on contact",
    description:
      "Unrefined shea butter whipped with oat lipids into an airy cream that calms reactive skin. A comfortable daily seal for face and neck.",
    price: 48,
    category: "moisturizers",
    concerns: ["hydration", "soothing"],
    size: "50 ml",
    shape: "jar",
    palette: {
      backdrop: "#faeee2",
      bottle: "#f2e2ce",
      cap: "#b98a55",
      accent: "#ffffff",
    },
    keyIngredients: [
      { name: "Unrefined shea butter", benefit: "Deep condition without greasiness" },
      { name: "Oat lipids", benefit: "Supports a calm skin barrier" },
      { name: "Bisabolol", benefit: "Soothes visible redness" },
    ],
    howToUse: [
      "Scoop a pea-sized amount with clean fingers.",
      "Press gently over face and neck.",
      "Use morning and night as your last step.",
    ],
    rating: 4.7,
    reviewCount: 428,
    badges: ["Vegan", "Small batch"],
    skinTypes: ["Dry", "Sensitive", "Normal"],
    stockNote: "Ships in 1-2 business days",
  },
  {
    id: "p-rooibos-radiance-toner",
    slug: "rooibos-radiance-toner",
    name: "Rooibos Radiance Toner",
    tagline: "Antioxidant dew for dull, tired skin",
    description:
      "Fermented rooibos and lactic acid gently lift the day away, leaving skin soft, even and ready for what comes next. No sting, no stripping.",
    price: 34,
    category: "toners",
    concerns: ["brightening", "texture"],
    size: "150 ml",
    shape: "flask",
    palette: {
      backdrop: "#f9e4df",
      bottle: "#e5a79b",
      cap: "#8c5347",
      accent: "#fff8f4",
    },
    keyIngredients: [
      { name: "Fermented rooibos", benefit: "Antioxidants that fight dullness" },
      { name: "Lactic acid", benefit: "Sweeps away dead surface cells" },
      { name: "Aloe leaf water", benefit: "Instant, cooling hydration" },
    ],
    howToUse: [
      "Sweep over clean skin with a cotton pad or palms.",
      "Use morning and night after cleansing.",
      "Always follow with SPF in the morning.",
    ],
    rating: 4.6,
    reviewCount: 356,
    badges: ["Vegan", "Gentle exfoliant"],
    skinTypes: ["Normal", "Combination", "Dull"],
    stockNote: "Ships in 1-2 business days",
  },
  {
    id: "p-kalahari-melon-mist",
    slug: "kalahari-melon-mist",
    name: "Kalahari Melon Mist",
    tagline: "A cool veil of hydration, any time of day",
    description:
      "Pressed Kalahari melon seed water in a fine mist that revives makeup, travel-tired skin and mid-afternoon slumps. Keep one in your bag.",
    price: 28,
    category: "toners",
    concerns: ["hydration", "soothing"],
    size: "100 ml",
    shape: "flask",
    palette: {
      backdrop: "#e4f0f3",
      bottle: "#bedde3",
      cap: "#4e7480",
      accent: "#ffffff",
    },
    keyIngredients: [
      { name: "Kalahari melon", benefit: "Lightweight, water-dense hydration" },
      { name: "Rose water", benefit: "Softens and refreshes" },
      { name: "Glycerin", benefit: "Draws moisture to the surface" },
    ],
    howToUse: [
      "Mist 20 cm from the face with eyes closed.",
      "Use before serum or over makeup to refresh.",
      "Reapply whenever skin feels tight.",
    ],
    rating: 4.7,
    reviewCount: 289,
    badges: ["Vegan", "Travel friendly"],
    skinTypes: ["All skin types"],
    stockNote: "Ships in 1-2 business days",
    isNew: true,
  },
  {
    id: "p-black-soap-gel-cleanser",
    slug: "black-soap-gel-cleanser",
    name: "African Black Soap Gel Cleanser",
    tagline: "Deep clean without the squeak",
    description:
      "Traditional black soap reimagined as a low-foam gel with salicylic acid to clear congestion while plantain ash keeps skin balanced.",
    price: 32,
    category: "cleansers",
    concerns: ["clarity", "texture"],
    size: "200 ml",
    shape: "pump",
    palette: {
      backdrop: "#ede6df",
      bottle: "#5b5248",
      cap: "#2e2a26",
      accent: "#f6f1ea",
    },
    keyIngredients: [
      { name: "Plantain ash", benefit: "Traditional clarifying cleanse" },
      { name: "Salicylic acid", benefit: "Clears pores and smooths texture" },
      { name: "Shea butter", benefit: "Keeps skin soft post-cleanse" },
    ],
    howToUse: [
      "Massage one pump over damp skin for 30 seconds.",
      "Rinse with lukewarm water.",
      "Follow with toner and moisturizer.",
    ],
    rating: 4.6,
    reviewCount: 502,
    badges: ["Vegan", "Clarifying"],
    skinTypes: ["Oily", "Combination", "Blemish-prone"],
    stockNote: "Ships in 1-2 business days",
  },
  {
    id: "p-aloe-cucumber-milk-cleanser",
    slug: "aloe-cucumber-milk-cleanser",
    name: "Aloe & Cucumber Milk Cleanser",
    tagline: "The softest way to start the day",
    description:
      "A silky, non-foaming milk that lifts sunscreen and grime without disturbing the barrier. Aloe and cucumber leave skin calm, never tight.",
    price: 30,
    category: "cleansers",
    concerns: ["soothing", "hydration"],
    size: "180 ml",
    shape: "pump",
    palette: {
      backdrop: "#e9f1e5",
      bottle: "#c6ddbc",
      cap: "#6e8a5d",
      accent: "#ffffff",
    },
    keyIngredients: [
      { name: "Aloe vera", benefit: "Cooling, reparative hydration" },
      { name: "Cucumber extract", benefit: "Calms reactive, heated skin" },
      { name: "Jojoba esters", benefit: "Dissolves makeup gently" },
    ],
    howToUse: [
      "Massage 2 pumps onto dry or damp skin.",
      "Add water to emulsify, then rinse.",
      "Use nightly as a first cleanse.",
    ],
    rating: 4.8,
    reviewCount: 374,
    badges: ["Vegan", "Fragrance-free"],
    skinTypes: ["Sensitive", "Dry", "Normal"],
    stockNote: "Ships in 1-2 business days",
  },
  {
    id: "p-moringa-detox-clay-mask",
    slug: "moringa-detox-clay-mask",
    name: "Moringa Detox Clay Mask",
    tagline: "Ten minutes to a clearer complexion",
    description:
      "Moringa leaf powder and kaolin clay draw out congestion while glycerin keeps the mask from cracking. Skin feels refined, never stripped.",
    price: 38,
    category: "masks",
    concerns: ["clarity", "texture"],
    size: "60 ml",
    shape: "jar",
    palette: {
      backdrop: "#e9eee2",
      bottle: "#8c9b77",
      cap: "#4a5741",
      accent: "#fdfbf3",
    },
    keyIngredients: [
      { name: "Moringa leaf", benefit: "Nutrient-dense antioxidant support" },
      { name: "Kaolin clay", benefit: "Lifts excess oil and debris" },
      { name: "Glycerin", benefit: "Keeps the mask comfortable" },
    ],
    howToUse: [
      "Apply an even layer to clean, dry skin.",
      "Leave on for 10 minutes - remove before it sets.",
      "Rinse with warm water and moisturize.",
    ],
    rating: 4.7,
    reviewCount: 465,
    badges: ["Vegan", "Weekly ritual"],
    skinTypes: ["Oily", "Combination", "Congested"],
    stockNote: "Ships in 1-2 business days",
    isBestSeller: true,
  },
  {
    id: "p-hibiscus-bloom-peel",
    slug: "hibiscus-bloom-resurfacing-peel",
    name: "Hibiscus Bloom Resurfacing Peel",
    tagline: "The gentler kind of glow",
    description:
      "Hibiscus and fruit acids dissolve dead cells overnight, revealing smoother, brighter skin by morning. Formulated to be used twice a week.",
    price: 44,
    category: "masks",
    concerns: ["brightening", "texture"],
    size: "50 ml",
    shape: "tube",
    palette: {
      backdrop: "#fbe6ea",
      bottle: "#d9738c",
      cap: "#8e3f55",
      accent: "#fff7f9",
    },
    keyIngredients: [
      { name: "Hibiscus flower acid", benefit: "Natural, gentle resurfacing" },
      { name: "Papaya enzymes", benefit: "Softens without scrubbing" },
      { name: "Licorice root", benefit: "Evens tone over time" },
    ],
    howToUse: [
      "Smooth a thin layer over clean skin at night.",
      "Leave for 10 minutes, then rinse.",
      "Use twice weekly, always with SPF the next day.",
    ],
    rating: 4.8,
    reviewCount: 318,
    badges: ["Vegan", "Overnight glow"],
    skinTypes: ["Normal", "Combination", "Dull"],
    stockNote: "Ships in 1-2 business days",
    isNew: true,
  },
  {
    id: "p-rosehip-renewal-night-oil",
    slug: "rosehip-renewal-night-oil",
    name: "Rosehip Renewal Night Oil",
    tagline: "Repair while you sleep",
    description:
      "A nightly blend of rosehip, sea buckthorn and bakuchiol that softens the look of fine lines and evens tone over time. Wake up with skin that feels bouncier.",
    price: 56,
    category: "serums",
    concerns: ["firming", "brightening"],
    size: "30 ml",
    shape: "dropper",
    palette: {
      backdrop: "#f6e4e4",
      bottle: "#d9a2a2",
      cap: "#7a4a4a",
      accent: "#fffbfb",
    },
    keyIngredients: [
      { name: "Rosehip oil", benefit: "Natural vitamin A for renewal" },
      { name: "Bakuchiol", benefit: "Plant retinol alternative, no irritation" },
      { name: "Sea buckthorn", benefit: "Rich in omegas 3, 6, 7 and 9" },
    ],
    howToUse: [
      "Use as the final step of your evening routine.",
      "Warm 3 drops and press over face, neck and chest.",
      "Start three nights a week, build up as tolerated.",
    ],
    rating: 4.9,
    reviewCount: 687,
    badges: ["Vegan", "Retinol alternative"],
    skinTypes: ["Mature", "Dry", "Normal"],
    stockNote: "Ships in 1-2 business days",
    isBestSeller: true,
  },
  {
    id: "p-turmeric-brightening-bar",
    slug: "turmeric-brightening-cleansing-bar",
    name: "Turmeric Brightening Cleansing Bar",
    tagline: "A solid cleanser that travels well",
    description:
      "Turmeric, honey and oats pressed into a palm-sized bar that lathers softly to brighten and calm. TSA-friendly and plastic-free.",
    price: 18,
    category: "cleansers",
    concerns: ["brightening", "clarity"],
    size: "100 g",
    shape: "bar",
    palette: {
      backdrop: "#faf0d9",
      bottle: "#ebcb7a",
      cap: "#9b7a2e",
      accent: "#fffdf6",
    },
    keyIngredients: [
      { name: "Turmeric", benefit: "Brightens and calms blemishes" },
      { name: "Raw honey", benefit: "Antibacterial, humectant sweetness" },
      { name: "Colloidal oats", benefit: "Soothes irritation and itch" },
    ],
    howToUse: [
      "Lather in wet hands or directly on skin.",
      "Massage for 30 seconds, then rinse.",
      "Store dry between uses to keep the bar firm.",
    ],
    rating: 4.6,
    reviewCount: 233,
    badges: ["Vegan", "Plastic-free"],
    skinTypes: ["All skin types"],
    stockNote: "Ships in 1-2 business days",
  },
  {
    id: "p-cocoa-butter-body-whip",
    slug: "cocoa-butter-body-whip",
    name: "Cocoa Butter Body Whip",
    tagline: "Whipped luxury from shoulders to soles",
    description:
      "A thick, whipped cocoa butter that melts into skin in seconds and keeps elbows, knees and shins soft for hours. Smells like a warm kitchen.",
    price: 36,
    category: "body",
    concerns: ["hydration", "firming"],
    size: "200 ml",
    shape: "jar",
    palette: {
      backdrop: "#f3e7dc",
      bottle: "#8a6244",
      cap: "#523524",
      accent: "#fbf5ee",
    },
    keyIngredients: [
      { name: "Cocoa butter", benefit: "Long-lasting richness" },
      { name: "Mango seed butter", benefit: "Softens and conditions skin" },
      { name: "Vitamin E", benefit: "Protects and smooths" },
    ],
    howToUse: [
      "Scoop generously onto damp skin after bathing.",
      "Massage in upward strokes.",
      "Focus on elbows, knees and any dry patches.",
    ],
    rating: 4.8,
    reviewCount: 411,
    badges: ["Vegan", "Small batch"],
    skinTypes: ["Dry", "Normal"],
    stockNote: "Ships in 1-2 business days",
    isBestSeller: true,
  },
  {
    id: "p-neroli-body-glow-oil",
    slug: "neroli-body-glow-oil",
    name: "Neroli Body Glow Oil",
    tagline: "Subtle sheen, not a slick",
    description:
      "A fast-absorbing body oil with neroli and baobab that dries down to a soft sheen. Layer over body cream for the look of a holiday glow.",
    price: 42,
    category: "body",
    concerns: ["hydration", "firming"],
    size: "120 ml",
    shape: "pump",
    palette: {
      backdrop: "#f2efe2",
      bottle: "#e3d9a8",
      cap: "#6e6b3e",
      accent: "#fffef8",
    },
    keyIngredients: [
      { name: "Neroli", benefit: "Calming, citrusy aromatherapy" },
      { name: "Baobab oil", benefit: "Restores suppleness" },
      { name: "Vitamin C ester", benefit: "Evens the look of body tone" },
    ],
    howToUse: [
      "Warm 4-5 pumps in your hands.",
      "Massage over damp, freshly showered skin.",
      "Let it absorb before dressing.",
    ],
    rating: 4.7,
    reviewCount: 198,
    badges: ["Vegan", "Aromatherapy"],
    skinTypes: ["All skin types"],
    stockNote: "Ships in 1-2 business days",
    isNew: true,
  },
  {
    id: "p-argan-honey-lip-treatment",
    slug: "argan-honey-lip-treatment",
    name: "Argan & Honey Lip Treatment",
    tagline: "The lip balm that never leaves your bag",
    description:
      "A cushiony balm of argan oil and candelilla wax that repairs dry, cracked lips overnight. Comes as a duo so one can live in each pocket.",
    price: 16,
    compareAtPrice: 22,
    category: "body",
    concerns: ["hydration", "soothing"],
    size: "2 x 12 g",
    shape: "tube",
    palette: {
      backdrop: "#f9e9e1",
      bottle: "#e4b79c",
      cap: "#84573c",
      accent: "#fff9f5",
    },
    keyIngredients: [
      { name: "Argan oil", benefit: "Feeds very dry lips" },
      { name: "Honey", benefit: "Draws in moisture" },
      { name: "Candelilla wax", benefit: "Plant-based protective seal" },
    ],
    howToUse: [
      "Sweep over lips as often as needed.",
      "Apply a thicker layer before bed.",
      "Use over lip liner for a soft gloss.",
    ],
    rating: 4.9,
    reviewCount: 156,
    badges: ["Vegan", "Set of 2"],
    skinTypes: ["All skin types"],
    stockNote: "Ships in 1-2 business days",
  },
];
